spring:
  application:
    name: CC_SERVICE
  profiles:
    active: mybatis, common, redis
mybatis:
  type-aliases-package: com.cc.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true